BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE FIREWORKS_SCRIPT_LOG';
    EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FIREWORKS_SCRIPT_LOG
 (
    INSTALLATION_ID VARCHAR2(255 BYTE),
    ACTION VARCHAR2(64 BYTE),    
    MODULE_NAME VARCHAR2(64 BYTE),    
    MODULE_VERSION VARCHAR2(128 BYTE),
    MODULE_REVISION VARCHAR2(64 BYTE),
	EXECUTED_SCRIPT VARCHAR2(255 BYTE),
	EXECUTED_ON TIMESTAMP
 );
 
 COMMIT;
 QUIT;
