CREATE TABLE FIREWORKS_SCRIPT_LOG
 (
    INSTALLATION_ID VARCHAR(255),
    ACTION VARCHAR(64),    
    MODULE_NAME VARCHAR(64),    
    MODULE_VERSION VARCHAR(128),
    MODULE_REVISION VARCHAR(64),
	EXECUTED_SCRIPT VARCHAR(255),
	EXECUTED_ON TIMESTAMP
 );